version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=dealbreaker
      - DB_NAME=postgres
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=dealbreaker
      - PG_DB=postgres